### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PaulHutchInMA** [pimylifeup/Raspberry-Pi-Sense-HAT-Digital-Clock#1]
I was looking to add this code to a project that I would like to release as FLOSS software. However you have no license for this code therefore copyright law prevents reuse. Could you please add a FLOSS compatible license.

**Comment by gus-0** [comment]
Hi @PaulHutchInMA 

I have added the MIT license.

**Comment by PaulHutchInMA** [comment]
Thank you so very much
